version: '3.9'

services:
  # MongoDB service
  # mongodb:
  #   container_name: db_container
  #   image: mongo:6.8.0
  #   restart: always
  #   volumes:
  #     - mongodb_data:/data/db

  # Redis service
  redis:
    container_name: redis_container
    image: redis:latest
    environment:
      REDIS_URL: ${REDIS_URL}
      REDIS_EXPIRATION: ${REDIS_EXPIRATION}
    volumes:
      - redis_data:/data

  # API service
  api:
    build: .
    ports:
      - '8080:8080'
    env_file:
      - ./config.env
    depends_on:
      - redis
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  redis_data:
