

services:
  # Redis service
  redis:
    container_name: redis_container
    image: redis:latest
    env_file:
      - ./config.env
    volumes:
      - redis_data:/data

  # API service
  api:
    build: .
    ports:
      - '8080:8080'
    env_file:
      - ./config.env
    depends_on:
      - redis

volumes:
  redis_data:
